### ISSUE TITLE
Safari 13.1 MacOS "TypeError: Attempted to assign to readonly property" with SDP "a=extmap-allow-mixed"

### ISSUE THREAD

**Issue by ea167** [webrtcHacks/adapter#1039]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Safari 13.1 MacOS

**adapter.js (e.g. 6.1.0)**
7.6.0

## Description
`TypeError: Attempted to assign to readonly property`
when calling `setRemoteDescription()` with an SDP containing `"a=extmap-allow-mixed"`

Error in `common_shim.js`, line 333:
desc.sdp = ...     is **read-only** and fails

## Steps to reproduce
Call `setRemoteDescription()`  with SDP containing `"a=extmap-allow-mixed"`

## Expected results
`setRemoteDescription()` to work without exceptions in Safari :)

## Actual results
`setRemoteDescription()` fails

**Comment by fippo** [comment]
you're calling pc.setRemoteDescription(new RTCSessionDescription({type: .., sdp: ...})?
RTCSessionDescription properties are technically read-only but past attempts by browser vendors to enforce this turned out to break too much. But safari didn't notice...

The easy workaround is to simply omit the "new RTCSessionDescription" bit and pass a json object. Will fix the other path though.

**Comment by fippo** [comment]
overtaken by events, new safari versions don't use this anymore.
