### ISSUE TITLE
Interfaces with the moz-prefix are now deprecated in Firefox Nightly 44.0a1

### ISSUE THREAD

**Issue by jhamfler** [webrtcHacks/adapter#140]
This is the link to the changes: https://bugzilla.mozilla.org/show_bug.cgi?id=1155923

This error is shown when trying to use an interface:
`WebRTC interfaces with the "moz" prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated. adapter.js:124:11`

Currently my Nightly crashes when trying to debug this. So far it seems that at this time a simple

```
if (webrtcDetectedVersion < 44) {
// ... function registered on window object here
}
```

is enough to permit this error but i havent found the others now.

**Comment by KaptenJansson** [comment]
@fippo FYI

**Comment by KaptenJansson** [comment]
@jhamfler Thanks for reporting. Have you reported the crash in the mozilla bug tracker?

**Comment by jhamfler** [comment]
No I thought reporting this here would be enough as the adapter should handle the compatibility.
I cannot find any other interface change in buzilla relating that so I guess changing the name would be enough. This comment seems to support this:
Martin Thomson [:mt:] 2015-04-17 16:39:03 PDT: "This API isn't going to change in a way that will break compatibility."

I can only hope that he is right.

**Comment by KaptenJansson** [comment]
Yes adapter should handle the removal of prefix until all firefox channels use the non-prefixed version. However a browser should not crash when using older prefixed versions of the API's.

**Comment by jan-ivar** [comment]
@jhamfler it is merely a warning, not an error, and everything should work as before, whether you use 'moz' prefix or no prefix. Nothing should fail (for now). We'll probably run like this for a couple of releases.

If you're seeing failures or crashes, please report them here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=WebRTC

AFAIK there is no compatibility issue or work for adapter.js here, since Firefox's new behavior is to spec, and everything should "just work".

Example: https://jsfiddle.net/aynr0k5q/ works for me in Nightly whether I remove line 4 `<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>` or not.

**Comment by jhamfler** [comment]
@jan-ivar 
Ok my Problem really seems to be a Firefox internal problem. I had wrong thoughts on that one.

I tested your example and it worked of course. What I do different is that I use a remote messaging server and I hold back ICE candidates until the remote description is set. Then an ICE error occurs and Firefox crashes. So ICE may be not working perfectly in the current Nightly but seems to work locally in one tab.

This test (connectivity section) supports that in my opinion: https://test.webrtc.org/

Therefore I think this issue can be closed.

**Comment by jan-ivar** [comment]
@jhamfler OK. Please file a bug on the crash though. Browsers should never crash: https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=WebRTC%3A%20Signaling

**Comment by jan-ivar** [comment]
Someone else needs to close this issue for me.
