### ISSUE TITLE
WebRTC data-channel detect/support of SCTP/RTP?

### ISSUE THREAD

**Issue by arturparkhisenko** [webrtcHacks/adapter#150]
Like in Atlassian [AdapterJS](https://github.com/Temasys/AdapterJS/blob/master/source/adapter.js#L391-L393) , or we dont need it?

**Comment by KaptenJansson** [comment]
Hi,

Judging by the code in the linked AdapterJS file this was needed back in the earlier days of WebRTC. 

I do not see the need for it now since most (I want to say all) browsers support this now.

Do you have a specific use case in mind that requires this kind of detection (assuming most browsers support it)?

**Comment by fippo** [comment]
RTP datachannels should not be used (and are in fact currently broken in Chrome).

**Comment by arturparkhisenko** [comment]
@KaptenJansson @fippo by default current browsers use SCTP (do i need send `optional: [ {RtpDataChannels: false}]`)? how to be with chrome ver. 24 - 30?

**Comment by fippo** [comment]
@ikeagold you don't need any special flags to enable sctp datachannels. Chrome 24 - 30 are more than two years old... the chance of anyone using those versions is rather small. and you'll run into interop issues with firefox.

**Comment by KaptenJansson** [comment]
Browsers are like food, consume them while they are fresh, stay away from the old and rotten ones ;).

**Comment by arturparkhisenko** [comment]
@fippo ok thanks, so we can close issue (i think i'm just implement that for old chrome).
