### ISSUE TITLE
Improve browserDetection logic/structure

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#211]
**Description**
Clean up the browserDetection structure in utils.js

**Comment by fippo** [comment]
apparently this also mis-detects safari as chrome. Now imo it is rather silly for safari/webkit to use the same prefixed webkitRTCPeerConnection that Chrome uses...

**Comment by vganapathy-lifesize** [comment]
Since I found this to be related to the issue I found thought of just commenting in here. Looks like adapter_core.js breaks on IE. If the utils returns browserDetails null it breaks if (browserDetails.version < browserDetails.minVersion). Possibly in the switch statement that follows as well. Need to deal with unsupported browsers a tad better.
