### ISSUE TITLE
framerate in firefox

### ISSUE THREAD

**Issue by MariasStory** [webrtcHacks/adapter#291]
**Browsers and versions affected**
Firefox - all versions.

**Description**
framerate in getusermedia (camera) does not work in Firefox.

**Steps to reproduce**
Use the framerate constrains in getusermedia example using Firefox

**Expected results**
Camera should use the given framerate constrains.
This works in Chrome.

**Actual results**
The camera uses default framerate ~30 frames.

**Comment by jan-ivar** [comment]
@MariasStory are you on OSX by any chance? If so, then this is [a known issue](https://bugzil.la/1180725) we're working on.

There's little adapter.js can do to remedy this limitation in Firefox on OSX. In the future you can file Firefox bugs [at this link](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=WebRTC).

If you are not on OSX, then please see [this SO answer](http://stackoverflow.com/questions/35516416/firefox-frame-rate-max-constraint/35566115#35566115) about browser differences with regard to what `getUserMedia` returns.

**Comment by MariasStory** [comment]
@jan-ivar so far I have tried linux and Win 8.1

Do you have (seen) any working example that can change framerate in FF?

**Comment by jan-ivar** [comment]
@MariasStory what camera do you have? Firefox returns native camera modes only, so what framerates you get depends on your camera.

It's not correct to expect that "Camera should use the given framerate constrains" if by that you mean it should return exactly the values you put in, since the spec doesn't mandate that behavior.

**Comment by KaptenJansson** [comment]
Cameras can never reliably provide a specific framerate due to how cameras work. If it gets too dark for the sensor and it has cranked up the ISO to the max it will start reducing it's framerate (effectively the shutter speed goes down) regardless if we had spec that mandated that behavior (I guess that's why it doesn't).

It's always a best effort although the browser can do some tricks provide the specified framerate to some extent by dropping frames if not supported natively (camera will still send the closest match native  framerate), I believe this is how Chrome does it.

**Comment by MariasStory** [comment]
@KaptenJansson thanks for the detailed comment and I agree that the constrains cannot be completely satisfied and in some cases just a software work around is used.

From my experience, there can be 3 scenario with the chrome constrains of (for example) 15 fps:
1. Frames have 15 fps with less noise and higher sensitivity (ISO). Often the case in Ubuntu.
2. Frames have 15 fps with software integrated (no ISO change) and have less noise. Win 8.1.
3. The camera does not switch on. The framerate cannot be set. Win.

So, in general I prefer to have the first scenario on both Chrome and FF. If the framerate cannot be set, the camera should use the closest available framerate. Even the scenario with software integration is acceptable as there is less noise and frames to transfer.

There is no effect of the framerate constrains in FF at all.

I know that the question is more to FF. I just wanted to make sure that I am not missing some points here.

I hope that you can see my point now.

Any help?

**Comment by jan-ivar** [comment]
@MariasStory to answer your earlier question, when I use https://jsfiddle.net/h85ntyL5/ which uses
`{ video: { frameRate: { max: 15} } }`, I see in Firefox (46) the following on my Dell Win 10 box with my Logitech C910:

```
Success: 1392x768
Framerate: ~15.00
```

As you can see, this is a fairly odd mode, far from the default 640x480, so don't expect all combinations of resolutions and framerate to be available. Again, your results may differ, ans this depends on your camera supports.

**Comment by MariasStory** [comment]
@KaptenJansson I think that these are native parameters of your camera. I also get hd and ~15 fps on your example. The problem is that I cannot change resolution :-(.

Try this modified (old school) example: https://jsfiddle.net/o5wv2cgy/

It does not work on Crome, but in FF it changes resolution (If possible). Although, the resolution is set properly, the framerate constrains do not work.

**Comment by jan-ivar** [comment]
@MariasStory That proves your camera does have some 15 fps modes, just not 640x480x15. Since Firefox does not drop frames, you're out of luck in getting that specific mode.

You haven't shared why getting this specific mode is important to you. You might want to take a step back and look at what problem you're trying to solve. Again, see the workarounds I linked to earlier.

PS: `minWidth` is non-standard and does nothing in Firefox, so I wouldn't read into anything in your fiddle.

**Comment by KaptenJansson** [comment]
Can we close this issue now since it's not related to adapter?

**Comment by jan-ivar** [comment]
Yes. In the future, Firefox bugs should be filed [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=WebRTC). I'm also happy to answer questions on [StackOverflow](http://stackoverflow.com/) tagged `[getUserMedia]` or `[webrtc]`.
