### ISSUE TITLE
SyntaxError: Unexpected token '>' (11:01:31:703 | error, javascript)   at adapter-latest.js:726

### ISSUE THREAD

**Issue by fatalfeel** [webrtcHacks/adapter#297]
http://webrtc.github.io/adapter/adapter-latest.js

SyntaxError: Unexpected token '>' (11:01:31:703 | error, javascript)
  at adapter-latest.js:726

**Comment by KaptenJansson** [comment]
Hi,

Where are you running this? It cannot run a ECMA 6 arrow functíon.

Is your browser/environment not ECMA 6 capable?

**Comment by fatalfeel** [comment]
firefox 41

**Comment by KaptenJansson** [comment]
Why are you using a browser from September 2015? Even FF ESR is on version 45. Please update.

cc @jan-ivar

**Comment by fatalfeel** [comment]
I am 32 bits windows system the lasetest version is v43 /

**Comment by KaptenJansson** [comment]
No, that is not true according to https://www.mozilla.org/en-US/firefox/46.0.1/system-requirements/.

**Comment by KaptenJansson** [comment]
Closing issue due to using ancient browser.

**Comment by fatalfeel** [comment]
SyntaxError: Unexpected token '>' (11:01:31:703 | error, javascript) fixed
///
but failed here
change to adapter.js or adapter-latest.js both failed too  wss can not work on firefox v46
https://picasaweb.google.com/106185541018774360364/IMx6#6285590650062588018

at chrome is ok
https://picasaweb.google.com/106185541018774360364/IMx6#6285592528799490258

**Comment by davies147** [comment]
I agree that suddenly using ECMA6 '=>' arrow functions is a bit out of
order. A useful function of adapter.js has always been to load adapter.js
to determine whether you can use WebRTC. There are companies running IE10,
IE11 etc out there because they have strict upgrade policies internally
(yes it might be stupid, but it happens).

IMHO adapter.js should be able to load on IE, older Firefox, and older
Chrome, and will fail gracefully rather than throwing a compile-time
exception. Perhaps a solution to this is to add some 'babel'ified targets
for people who need them?

At the very least the README.md should warn that backward compatibility
just got thrown out?

Cheers,
Steve

**Comment by KaptenJansson** [comment]
Yes I agree. I did not realize the impact it would have. Will merge @fippo's fix.

**Comment by KaptenJansson** [comment]
This has now been fixed. Thanks for your feedback. Will look into adding babelified targets soonish for legacy browsers.

**Comment by fatalfeel** [comment]
thanks man~~~~great

**Comment by davies147** [comment]
Awesome turnaround. Many thanks.

**Comment by jan-ivar** [comment]
This is odd. Firefox has supported arrow functions since Firefox 22...
