### ISSUE TITLE
Firefox deprecated mozGetUserMedia

### ISSUE THREAD

**Issue by aszmyd** [webrtcHacks/adapter#310]
Because of this line: https://github.com/webrtc/adapter/blob/master/src/js/firefox/firefox_shim.js#L207 Im getting warning `navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia` using Firefox. Our app is behaving weirdly using adapter and i wonder if it shouldn't be updated on Your side.

![image](https://cloud.githubusercontent.com/assets/3050805/15495048/05e38c48-218e-11e6-8fa7-32b15c11aaa4.png)

**Comment by KaptenJansson** [comment]
@jan-ivar I do not think we should return a non shimmed api at https://github.com/webrtc/adapter/blob/master/src/js/firefox/firefox_shim.js#L207, WDYT?

**Comment by jan-ivar** [comment]
@KaptenJansson I'll take care of it.

**Comment by jan-ivar** [comment]
@aszmyd are you calling `navigator.getUserMedia` by any chance? I can't figure out how you would see this message otherwise. Arguably, `navigator.getUserMedia` is [also deprecated](http://w3c.github.io/mediacapture-main/getusermedia.html#navigatorusermedia-interface-extensions), though I agree the error message is confusing.

**Comment by jan-ivar** [comment]
"Fix" above updates warning to point to use of `navigator.getUserMedia`.

**Comment by aszmyd** [comment]
@jan-ivar we've been using `v0.2.9` for our project for some time and now wanted to use the new, refactored version. I thought adapter is making `navigator.getUserMedia` available on every supported browsers (just dealing with browser prefixes). I cannot find any docs of how to use the adapter differently?

**Comment by KaptenJansson** [comment]
Thanks @jan-ivar for the fix!

**Comment by aszmyd** [comment]
@KaptenJansson maybe You can answer to my question about different way of usage new adapter? Any up to date docs somewhere?

**Comment by KaptenJansson** [comment]
Ow right sorry forgot your question. The standard depicts the use of `navigator.mediaDevices.getUserMedia` hence I recommend you start using that instead even though `navigator.getUserMedia` does work (we did have a bug though in the shim were we returned it rather than a shimmed variant).

The refactored version is split into modules and then browserfied to one file that you can use in your project (do `grunt build` and the check the `out/` folder or use compiled versions on the [gh-pages](https://github.com/webrtc/adapter/tree/gh-pages) branch directly). 

It no longer exposes things in the global scope except for `adapter` (although we have variants which does not expose anything, see [README.md](https://github.com/webrtc/adapter/blob/master/README.md)) and just shims the API's quietly (e.g. shimmed chrome APIs [here](https://github.com/webrtc/adapter/blob/master/src/js/adapter_core.js#L46-L50)) which you can use directly. To see what is exposed under the `adapter` object check [here](https://github.com/webrtc/adapter/blob/master/src/js/utils.js#L138).

You can read [README.md](https://github.com/webrtc/adapter/blob/master/README.md). Please file bugs about concrete stuff that you think is missing from this readme and I will try to add them.

Thanks!
