### ISSUE TITLE
Include dist files in releases for proper package handling

### ISSUE THREAD

**Issue by klasjersevi** [webrtcHacks/adapter#339]
The current solution with all releases in one branch makes it impossible to track new versions in package managers such as bower.

Suggested solution
Include the corresponding built dist-files with version releases (like most projects do).
This would make it possible to make use of proper version handling when using bower and other package manages who rely on the semver version tags in the git repo.

**Comment by KaptenJansson** [comment]
I tried that but bower reads directly from the github repo and we do not want to check in built dist files in the master repo. While NPM is published explicitly and pushed to the npmjs registry. On publish it runs the build command and excludes the files in .npmignore or .gitignore.

AFAIK Bower has no such feature (there are some hacks for this but did not see the value).

Also do note that we do want to serve adapter from gh-pages so that web pages can directly link to them in their app.

And you can only make one release per repo, i.e. we cannot create v1.0.5 for the master and gh-pages branch, it would be v1.0.5 for master and v.1.0.6 for gh-pages.

One question, generally,  developers using bower, do they not use NPM at all?

**Comment by klasjersevi** [comment]
I can see the point with the gh-pages for serving to the web, but the fact remains that it's difficult to use this repo with bower as it is. Maybe the gh-pages should be moved to a separate repo for full flexibility?

Developers I know that make web projects generally use NPM for tools and frameworks regarding building and testing their projects such as grunt, gulp, less, sass, uglify, linting etc, while Bower is used for handling distributed lib dependencies such as jQuery, Bootstrap and in my case the WebRTC adapter.

**Comment by klasjersevi** [comment]
I created my own fork to get what I needed, feel free to pull it if you like (really no big changes more than including the dist files)

https://github.com/Mindroute/adapter

My suggestions for a cleaner and more compliant distribution:
- Include the built files in out folder.
- Rename the built file to something that makes it reflect the whole name, e.g. webrtc-adapter.js
- Include version number and origin in a comment in the beginning of the built files.
- Change the main in bower.json to point to the main dist file.
- Move gh-pages to another repo. In my opinion, branches should mainly be used for different offsprings of the master branch, such as an old or modified version.

**Comment by KaptenJansson** [comment]
I see your point but we (WebRTC) are only using NPM to fetch adapter for our projects. Do you have any data of how many use bower to fetch adapter (or is that something I can gather)? I'm not against it, but I would really not like having compiled files checked. Do you have examples of bigger projects where they check in compiled code in the master branch in order to distribute similar to this?

Why move gh-pages? It's known that it is special branch in GitHub for (generally) serving static content for the web. Sure, how it's currently structured and it's content can be questioned but not the existence and purpose of the branch itself IMHO.

**Comment by klasjersevi** [comment]
Well, you already have all the compiled files in the repo, so it's more a matter where in the repo you have them. I just think you should have them accessible by release version in a more standard way to get better version control for the distribution.

There are also alternatives to the way to do this. You could make another bower-repo with just distributed files, which some projects do. However, it's always nice to be able to modify and rebuild it yourself if you need to. You can also do like jQuery does and just include the dist files when making a release and then remove them again right after to avoid usage of unreleased builds.

Examples of repos with distributed files:
https://github.com/jquery/jquery
https://github.com/twbs/bootstrap
https://github.com/moment/moment
https://github.com/mrdoob/three.js
https://github.com/twitter/typeahead.js

**Comment by KaptenJansson** [comment]
Thanks for this, will take a look.

**Comment by KaptenJansson** [comment]
Sorry for the delay, will take another look now.

**Comment by KaptenJansson** [comment]
Done. Please try out and see if it works for you. I will update the README.md file shortly.

**Comment by klasjersevi** [comment]
Wonderful! Works like a charm! Thank you @KaptenJansson for considering this!

**Comment by KaptenJansson** [comment]
No worries, glad I could help.
