### ISSUE TITLE
addStream deprecated

### ISSUE THREAD

**Issue by tleunen** [webrtcHacks/adapter#361]
From https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream

> This method has been deprecated; you should, compatibility allowing [2], switch to using the addTrack() method instead.

The adapter doesn't seem to set the `addTrack` function on a PC.

**Comment by fippo** [comment]
this is impossible to shim in Chrome right now. @KaptenJansson do you know the chrome bug for tracking this?

**Comment by KaptenJansson** [comment]
I know the ontrack event is implemented but unsure about addTrack. @alvestrand do you know?

**Comment by alvestrand** [comment]
Not added AFAIK.

Filed https://bugs.chromium.org/p/chromium/issues/detail?id=642712

A shim that works for the no-stream-given case (create a stream from the track, then discard the stream) should be easy to add. Whether it's useful is another matter.

**Comment by tleunen** [comment]
What about `removeTrack`?
because `removeStream` is also deprecated obviously and Firefox doesn't have the function.

**Comment by jan-ivar** [comment]
@tleunen `pc.removeTrack` (perhaps confusingly) takes a sender as an argument, which means we'd also need to shim `pc.getSenders()` (doable to a point). In Chrome I've had luck removing a stream from the peerConnection, then removing a track from the stream, and re-adding it to the peerConnection. Unfortunately, `pc.removeTrack` is not supposed to remove a track from its stream, so we can't shim it that way without side-effects (I haven't tried what happens if I add the track back to the stream after, if that triggers another renegotiation or not). Also, is there value in shimming one but not the other?

**Comment by KaptenJansson** [comment]
I noticed that addTrack did not work in AppRTC when I updated from 2 to 3.x.

**Comment by jan-ivar** [comment]
@KaptenJansson Do you have more info? We don't shim `addTrack` because of the difficulty of doing so mentioned in this thread. I couldn't find any references to `addTrack` or `getSenders` in apprtc with a quick scan. Did you mean `addStream`?
