### ISSUE TITLE
What about minimizing sdp?

### ISSUE THREAD

**Issue by MariasStory** [webrtcHacks/adapter#387]
**Browsers and versions affected**
All
**Description**
This one is somewhat old solution and may need to be updated:
https://www.npmjs.com/package/sdp-minimizer
https://github.com/fippo/sdp-minimizer

This part can often break and need to be maintained.

**Steps to reproduce**
Check sdp.

**Expected results**
Smallest sdp possible.

**Actual results**
Constant text transferred during the sdp exchange.

**Comment by fippo** [comment]
adapter is a shim for hiding incompabilities between browsers. Anything beyond that is out of scope.

Minimizing SDP is a stupid idea for a number of reasons (and I am saying that with my authors hat on)

**Comment by MariasStory** [comment]
Hi @fippo,
thanks for the fast answer.
Let me pretend to be stupid ;-). If I am right, the idea of the sdp exchange is to use another channel than the one that can be monitored/spied. I am sure that you know about the server less solutions. My point is that there should be a small sdp for the possibility of doing the exchange over E-mail/chat/sms or another channels.
I see your point that this problem may be out of scope and I agree that the solution should be flexible. I strongly disagree that the idea is stupid.

**Comment by fippo** [comment]
SDP negotiates the capabilites of both parties -- codecs, encryption and a lot of things needed for ICE. This is a complex problem and SDP is complex because of that.
Note that in WebRTC SDP (or rather: JSEP) is an API for passing things from JS to the browser. It does *not* say anything about what you do on the wire.

sdp-minimizer (see also [the webrtchacks post](https://webrtchacks.com/the-minimum-viable-sdp/) that describes the ideas behind it) makes a very large number of assumptions. That you only need a data channel, are ok with only relay candidates, ignore large parts of information from ice etc. I am pretty sure that the package as-is is not even fully interoperable between chrome and firefox.
Those assumptions are not valid for the vast majority of use-cases.

**Comment by KaptenJansson** [comment]
@alvestrand

**Comment by alvestrand** [comment]
Agreee with @fippo - this is out of scope for adapter.js.
There seems to be no disadvantage in keeping this as a separate component for people who want it.
