### ISSUE TITLE
need upgrade path to chrome's spec stats

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#389]
Chrome Canary just landed spec-style stats and they're great.
Now we have an issue we avoided for a very long time: how to upgrade from chrome-stats to legacy stats.

When getStats is called with anything not a function as the first argument we shim from the legacy stats:
https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L114-L118
This was good because we could determine whether the user was interested in the chrome stats or a more spec-style statistics. Now the defintion of "spec-style" has changed since we made that decision.

How do we determine whether
a) the user wants spec stats
b) the browser supports it. webrtcdetectedbrowser >= 57 doesn't work since that would mean legacy stats in opera for a looooong time (see also [here](https://lists.w3.org/Archives/Public/public-webrtc/2016Dec/0006.html))

Also how to deal with old chrome versions (real-world concern, even though appear.in officially only supports the latest two chrome versions we don't enforce this). I wonder if it makes sense to take @henbos' document and take another stab at writing the JS shim...

**Comment by KaptenJansson** [comment]
@henbos and @alvestrand could you please share you thoughts?

**Comment by alvestrand** [comment]
Hm. Is it possible to detect that there are 2 getStats functions, and what the difference is?

We can detect what the user wants:
- arg is function: Old-style
- arg is missing: new-style
- arg is object: new-style

but we have to detect what the browser supports too.
(the webrtcdetectedbrowser thing just shows that we need to be able to separate Opera from Chrome.)

**Comment by fippo** [comment]
I'm in favor of arguments.length === 0 => new style. So far the samples have shown track with an explicit null and I use that in my code as well. This should be a major version bump for adapter.

**Comment by henbos** [comment]
Note: It's available in Canary *behind a flag* (Experimental Web platform feature), PSA: https://groups.google.com/forum/#!topic/discuss-webrtc/7TXEazn9kTg

The two getStats functions (RTCPeerConnection.idl):
```
[CallWith=ScriptState, LegacyInterfaceTypeChecking] Promise<void> getStats(RTCStatsCallback successCallback, optional MediaStreamTrack? selector);
[CallWith=ScriptState, RuntimeEnabled=RTCPeerConnectionNewGetStats] Promise<RTCStatsReport> getStats(optional MediaStreamTrack? selector);
```

Based on arguments it's simple to figure out which function the caller wants to invoke ("is the first argument a function?"), but I don't know JavaScript well enough to know if there is a way to check if the second getStats function exists or not without trying to call it? In both cases, RTCPeerConnection.prototype.getStats exists with typeof as 'function'.

If we figure out we want to call the new getStats but it isn't available, we could either shim to the old getStats (returning something rather than nothing in case the caller can handle both types of stats), return no stats (there are no new stats available after all), or throw an exception (no, too aggressive?).

**Comment by fippo** [comment]
I might have found a way to check support. 
legacy
```webkitRTCPeerConnection.prototype.getStats.length```
is 1 (in M53, 2 in M55) With the web platform flag enabled,
```RTCPeerConnection.prototype.getStats.length```
is 0 in Canary/M57 . Without the flag it is 2.

I think this makes sense since the new signature only has an optional argument. Maybe someone who understands WebIDL better than me (say @foolip?) can confirm this?

**Comment by alvestrand** [comment]
(crossposting with fippo)

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype it seems that you can check pc.getStats.length for the number of arguments expected by a function. The old stats have length 2.

Complication: Since the name is an overload, I suspect that the prototype value is still 2 when you have the new stats function. (but fippo says it's 0. Shortest length wins?)
It might be reasonable for adapter.js to shim new-style getStats like this:

<pre>
function getStats() {
try: // in case of browsers so old, they don't return the dummy promise
  p = pc.getStats();
  if (p.rejected) {
     p.catch(error)(function(e) {
       // Check that it's TypeError, and if so:
       p = new Promise(pc.getStats(......forget the details here ....))
  }
  return p;
catch:
  // shim getstats as before
}
</pre>

**Comment by henbos** [comment]
Interesting! I hope this is by design and not a happy accident of undefined behavior for which length to show when there are multiple signatures :)

**Comment by henbos** [comment]
What do you think about rejecting the promise if user tries to call new getStats but it isn't enabled?

**Comment by alvestrand** [comment]
If new getstats is not enabled, we should fall back to behavior of previous version - that is, we shim it.

**Comment by fippo** [comment]
I'd do this before https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L114
```
if (RTCPeerConnection.prototype.getStats.length === 0 && arguments.length === 0) {
  return origGetStats();
}
```
But this doesn't solve the question what we do when a selector is passed.

We might consider determining support before fiddling with the prototype.

**Comment by henbos** [comment]
If called with just a selector argument we should call the new getStats as well. At the moment the new getStats ignores the selector argument, but that will change and it shouldn't shim just because you have a selector.

**Comment by fippo** [comment]
Yes but currently there is code out in the wild using adapter that calls getStats(null).then(...)

Maybe the most pragmatic thing here is to do a major version bump of adapter and say that you get spec-stats whenever you call getStats not in the legacy style.

**Comment by henbos** [comment]
I think we should do a major version bump and then let all spec-compliant calls to getStats go to the spec-compliant getStats if available. Since it is a disruptive change to get a different set of stats no matter how we proceed we might as well go the whole way to avoid having to do a second major bump in the future.

**Comment by KaptenJansson** [comment]
Last comment SGTM!

**Comment by fippo** [comment]
the slightly less bumpy way here would be to add a adapter.setStatsStyle API. This would be called once and would set whether the shim returns legacy stats or new stats.

This means extra effort however (tests) and I am not sure I am willing to pay it. Added a commit to #390

wrt to breaking stuff I am slightly worried that we tell people to use adapter-latest from gh-pages.

**Comment by KaptenJansson** [comment]
Well adapter-latest comes with that caveat unfortunately! They have to then lock on to a version instead, i.e. the last 2.x.x version.

**Comment by KaptenJansson** [comment]
I just wonder if all adapter consumers pay attention to the repo or if we need shout out the changes somewhere?

**Comment by fippo** [comment]
we can do the usual PSA on discuss-webrtc

**Comment by KaptenJansson** [comment]
Yeah will do.

**Comment by henbos** [comment]
I think we should either wait or have a setStatsStyle. If it's behind a flag when we do the change then the vast majority of calls will continue to yield the old stats style and not raise the warning to the developers that the stats have changed. Ugh, I don't like the idea of having a call that is supposed to return one style but falls back on another style. As a caller you'll have to be prepared for both without a failure and explicit code path to the old getStats.

**Comment by fippo** [comment]
Even after this ships you'll have to deal with legacy versions of Chrome and stats for a long while.
Maybe we should take two steps
1) require maplike, allow opt-in for spec-stats until they're generally available (major version 3)
2) make spec-stats the default (major version 4 or something)

This also makes shimming this in JS somewhat attractive. Maybe we should pick up https://github.com/webrtc/adapter/pull/124 again? I'd actually restart from scratch, your document is is a much better starting point than the organically grown code there

**Comment by foolip** [comment]
Regarding https://github.com/webrtc/adapter/issues/389#issuecomment-265986751, yes, using the function's `length` is a good way to detect support for the new getStats.

However, avoid any code like `webkitRTCPeerConnection.prototype.getStats.length` that isn't already inside an `if (window.webkitRTCPeerConnection)`, since otherwise that'd start throwing exceptions if we ever attempt to remove the `webkitRTCPeerConnection` alias.

**Comment by henbos** [comment]
Don't forget the "Promise getStats(selectorArg)" case.

**Comment by henbos** [comment]
Actually, the selector is currently ignored by Chromium's implementation. If this is not implemented I guess we should only ship the parameterless veriety. @alvestrand and I discussed the possibility of other types of selector arguments.

**Comment by fippo** [comment]
but the selector is optional in the IDL which means it would not be counted? @foolip please holler if I am wrong

(I don't like the selector... I do not see how it is going to work in the snowball model; but that is a discussion for the w3c list)

**Comment by henbos** [comment]
Yeah but if we don't do anything with a non-null selector maybe "getStats(non-null selector)" should not exist and throw an exception since it is not a call to the callback-based function. Unless we are sure we are going to implement it ASAP.

**Comment by foolip** [comment]
@fippo, if by "not counted" you mean that optional arguments do not affect the function's `length` attribute, that is correct.

This means that it's very difficult to detect when an optional argument is added, as @henbos suggests one would have to test if `pc.getStats(window)` or similar returns a rejected promise, which can't be done synchronously.

So, it'd be very good to decide to some certainty the fate of the selector argument now.

**Comment by henbos** [comment]
+ @alvestrand

**Comment by fippo** [comment]
we did that. Now we're waiting to see how much stuff breaks when it gets unflagged ;-)

**Comment by henbos** [comment]
The selector discussion is ongoing https://github.com/w3c/webrtc-pc/pull/990
In the meantime Chrome is unflagging (in Canary already) parameterless new getStats API for M58.
(Speaking of breaking, I broke the apprtc demo loopback case, fix being rolled in today...)
