### ISSUE TITLE
webrtc-adapter is not getting last device for facingMode environment anymore on Chrome

### ISSUE THREAD

**Issue by nicolashenry** [webrtcHacks/adapter#492]
**Browsers and versions affected**
Chrome Version 57.0.2987.132

**Description**
webrtc-adapter 3.3 is not getting last device for facingMode environment anymore when chrome which lies with facingMode is detected. This change seems to have been done here :
```
-            var back = devices.find(function(d) {
-              return d.label.toLowerCase().indexOf('back') !== -1;
-            }) || (devices.length && devices[devices.length - 1]);
-            if (back) {
-              constraints.video.deviceId = face.exact ? {exact: back.deviceId} :
-                                                        {ideal: back.deviceId};
+            var dev = devices.find(function(d) {
+              return d.label.toLowerCase().indexOf(match) !== -1;
+            });
+            if (dev) {
+              constraints.video.deviceId = face.exact ? {exact: dev.deviceId} :
+                                                        {ideal: dev.deviceId};
```
I think this part is missing in 3.3 for back camera : 
```}) || (devices.length && devices[devices.length - 1]);```

**Steps to reproduce**
Use getUserMedia with Chrome on android with ```facingMode: 'environment'```

**Expected results**
To get the back camera

**Actual results**
Got the front camera

**Comment by fippo** [comment]
@jan-ivar can you take a look?

**Comment by jan-ivar** [comment]
@nicolashenry What camera model do you have, if I may ask?

Yes I [removed](https://github.com/webrtc/adapter/pull/483) that part of the logic, after I learned the Surface Pro 4 defaults to the back camera, so I thought that assumption might not be good anymore.

Turns out I also messed up that patch for Surface Pro 4 (I should have tested for `"rear"` as well as `"back"`), so I need another patch. I'll put that logic back. Still curious what camera you have though.

**Comment by jan-ivar** [comment]
@nicolashenry Can you confirm that https://github.com/webrtc/adapter/issues/495 fixes your problem?

**Comment by nicolashenry** [comment]
@jan-ivar I had to launch grunt task to regenerate adapter.js from your branch. It works perfectly using the generated file. :+1:
