### ISSUE TITLE
Chrome runs 52 test while FF runs 36

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#51]
I've not dug into why, most likely a shim difference that accounts for this but still wanted to file an issue to remind me (or someone else) to really determine why.

**Comment by alvestrand** [comment]
if you're seeing this on travis, can you give links to the runs?
alternatively the command lines you're using, with the BROWSER and BVER envars?

**Comment by KaptenJansson** [comment]
32 for firefox beta - https://travis-ci.org/webrtc/adapter/jobs/67002072
38 for Firefox stable - https://travis-ci.org/webrtc/adapter/jobs/67002071

**Comment by alvestrand** [comment]
The difference between the two firefoxen is that stable returns this for enumerateDevices:

ok 36 valid enumerateDevices output: [{"kind":"audioinput","deviceId":"default","label":"","groupId":""},{"kind":"videoinput","deviceId":"default","label":"","groupId":""}]

beta returns this:

ok 30 valid enumerateDevices output: []

The extra tests are in a loop running over the device enumeration result.
I think beta's output is more correct, since the travis machines (presumably) don't have audio or video input.

Chrome (stable and beta) also runs 32 tests in that iteration, and has enumerateDevices output of [].
Running the tests locally SHOULD produce quite different results, due to the presence of devices.

Later runs also run more tests for Chrome, since they include the tests for "originalChromeGetStats".

Closing this bug as "investigated enough".

**Comment by jan-ivar** [comment]
We could take out the conditional tests, since conditional tests are arguably not very useful. Thoughts?

**Comment by alvestrand** [comment]
I think conditional tests are much more useful than no tests - for instance, the Chrome stats-massage tests are extremely important for Chrome users, but Firefox users won't be affected if they break, so it makes sense to only run them on Chrome.
