### ISSUE TITLE
Chrome DOMException: Track already exists for fake devices

### ISSUE THREAD

**Issue by adamweeks** [webrtcHacks/adapter#557]
When running automation tests, we open two chrome instances and call each other. We use the following options to use fake devices in Chrome:
* `--use-fake-device-for-media-stream`,
* `--use-fake-ui-for-media-stream`

Since version 3.4.1, we are getting `DOMException: Track already exists` error on our second instance when attempting to answer a call. 

This error did not happen in prior versions and test calls were able to be established properly.

Chrome version 58 on mac.

**Comment by fippo** [comment]
hrm. Do those tests use addTrack when available?

This is probably the exception [thrown here](https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L108) so i wonder why it is thrown. What is the sequence of events your test calls?

**Comment by adamweeks** [comment]
Our tests places a call from browser A to browser B. The error is thrown when browser B attempts to answer the call. This is where we are adding tracks: https://github.com/ciscospark/spark-js-sdk/blob/master/packages/node_modules/@ciscospark/plugin-phone/src/webrtc.js#L39

**Comment by fippo** [comment]
Hrm. That code looks like you're trying to solve exactly the problem the addTrack shim is supposed to solve.

I've come close to weird behaviour in https://jsfiddle.net/9awhwp03/
 -- if you use pc.getLocalStreams() instead of the saved stream things go wrong. 
But not the same error you get.

I think the root cause is using pc.getLocalStreams() which returns a different stream than what you expect. Using getLocalStreams() (a stream-based webrtc api) together with addTrack (track-based) is somewhat underspecified.

**Comment by jan-ivar** [comment]
@fippo Looks like they're keeping track of all local tracks in the same local stream. That should work in Firefox. They probably do it for symmetry with addStream in Chrome, which makes sense to me.

This would trip up your Chrome shim which does the same thing. Since the track is already where it needs to be, might it suffice to suppress the error?

**Comment by fippo** [comment]
Still trying to replicate. Even copying the code into a fiddle https://jsfiddle.net/ofssnscp/ I get a different error (the track is now part of multiple streams) so i'm missing a step.

**Comment by fippo** [comment]
I made the code work with two modifications:
1) get rid of pc.getLocalStreams
2) conditionally remove the "silly hack" if pc.addTrack exists

I think the first can be avoided by modifying pc.getLocalStreams together with shimming pc.addTrack.

**Comment by jan-ivar** [comment]
From my reading of the spec, this should be allowed, and not throw:
```js
pc.addStream(stream);
let track = await navigator.mediaDevices.getUserMedia({audio:true});
stream.addTrack(track); // <---
pc.addTrack(track, stream); // should not throw
```

**Comment by fippo** [comment]
https://jsfiddle.net/yx5fwxb0/ does not throw.
https://jsfiddle.net/yx5fwxb0/1/ does not throw but leads to an error.
https://jsfiddle.net/yx5fwxb0/2/ adds a getLocalStreams shim which avoids the error. Seems like the right thing to do?

**Comment by fippo** [comment]
tried the thing in the third fiddle and added a test. WDYT?

(i'm not happy but... *shrug*)

**Comment by ianwremmel** [comment]
So, it sounds like this error is happening because, in the current form of the adapter, `pc.addTrack(track, stream)` doesn't make that stream available via `pc.getLocalStream()`. Is that accurate?

**Comment by fippo** [comment]
yes, pc.getLocalStreams() returns something that is not usable again in addTrack. If you can give the change from #559 a try that would be great
