### ISSUE TITLE
Add helper function for stopping all tracks, all video and all audio tracks.

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#58]
Saves us from doing this in tons of places:
stream.getAudioTracks().forEach(function(track) { track.stop(); })

I propose adding the following methods:
stream.stopAllTracks()
stream.stopAllVideoTracks()
stream.stopAllAudioTracks()

@fippo, @juberti WDYT?

FYI: Note that Chrome actually has a non standard method called stream.getAllTracks().

**Comment by fippo** [comment]
how about shimming just shimming stop()? Which is currently supported in both Firefox and Chrome so we'd just need to do it for Edge.

(not sure why the stop method was removed from the spec for local MediaStreams, this behaviour is useful. @alvestrand?)

**Comment by alvestrand** [comment]
stream.stop() was removed because the WG thought it was so easy to shim, it was not worth specifying it. We were on a binge to remove functionality from streams at the time....

Adapter.js has a few helper functions that are used enough, they're likely not to go away. I don't think shimming stop() would make a big difference to the maintainability.

Note: The spec has a function getTracks() (rather than getAllTracks()) - we should DEFINITELY shim that.

**Comment by fippo** [comment]
we don't need to shim getTracks() even... it's there and works in all three browsers. Will update the samples, this removes one line at least.

I'll also check if we can easily shim stop() in Edge that way.

**Comment by KaptenJansson** [comment]
LGTM on using getTracks(), @alvestrand WDYT?

**Comment by fippo** [comment]
hrm... it seems that shimming is possible but calling track.stop() doesn't have any effect in Edge. Will poke some people to find out if that's a known bug.

**Comment by KaptenJansson** [comment]
It would be great if we could get some Edge developers to start contributing here as I assume there will be quite a lot of shimming needed for a while.

**Comment by kashifshamaz21** [comment]
@fippo I guess the `track.stop()` method is part of the spec, but not implemented by either of chrome/firefox as well. Check the comments on the answer in this link:
http://stackoverflow.com/questions/18174194/how-to-remove-track-from-mediastream-and-stop-webcam

The spec though talks about such a method on the track:
http://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediastreamtrack-stop

**Comment by alvestrand** [comment]
The track.stop method is defined in my version of Chrome at least.
at least going to the javascript console and typing "MediaStreamTrack.prototype.stop" returns "function stop()".
You will note that the stackoverflow question referenced is 2 years old. Things change.

**Comment by KaptenJansson** [comment]
FTR MediaStream.stop() was implemented and used until
MediaStreamTrack.stop() was implemented then the former was deprecated I
believe.

**Comment by kashifshamaz21** [comment]
@alvestrand yep, you are right. My bad, that is a very old post that i referred to, so pls ignore that comment. 
Just so that i understand it better, is the `MediaStream.stop()` API deprecated in the spec? And does invoking those methods in  latest versions of chrome/firefox show a deprecation warning? I'll try out and post back with results, but if anyone knows about it, pls enlighten! :)

**Comment by alvestrand** [comment]
@kashifshamaz21 the MediaStream.stop() isn't just deprecated in the spec, it's removed.
Someone needs to post a bug so that we get a deprecation warning into Chrome. Won't fix today.

**Comment by fippo** [comment]
The removal of stop() is tracked in https://code.google.com/p/chromium/issues/detail?id=338500
(and https://code.google.com/p/chromium/issues/detail?id=233545 ?)

"this needs to be announced to out users first" -- let's do that now? We can even tell people that they can continue to use it with adapter.js :-)

**Comment by jan-ivar** [comment]
Wanted to pipe in here that both MediaStream.stop() and MediaStreamTrack.stop() are still implemented in Firefox fwiw. Does this belong in the same bucket as https://github.com/w3c/webrtc-pc/issues/245 ?

As to shimming, maybe I got it wrong, but I thought we wanted adapter.js to shim _new_ APIs on _old platforms_, not the other way around, and that we wanted to remove obstacles from spec adoption, not addict people to adapter.js forever. ;)

To me that means fewer helper functions, not more of them, so I vote to close this.

Unfortunately, I don't see an easy way to shim track methods on platforms with only stream methods.

**Comment by KaptenJansson** [comment]
OK for closing this?

**Comment by alvestrand** [comment]
Seems right to med. Adapter's goal is not helpers.

Den 25. juli 2015 12.01.23 CEST, skrev Christoffer Jansson notifications@github.com:

> OK for closing this?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webrtc/adapter/issues/58#issuecomment-124829756

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fippo** [comment]
+1 -- iterating over getTracks() is a reasonable one-liner. And we just wanted to avoid iterating over both getAudioTracks() and getVideoTracks()

**Comment by thijstriemstra** [comment]
Anyone know why `MediaStreamTrack.stop` works on Chrome (turns off camera light) and doesn't work on Firefox (41 on osx 10.10)? I was hoping to find the answer in the adapter code but seems nobody came across this issue (yet).

**Comment by alvestrand** [comment]
@thijstriemstra if this happens if you call track.stop() on a MediaStreamTrack on Firefox, I suggest you file a bug on Firefox. I don't think we have a test for this in the adapter test suite (and I don't think adapter touches the stop() function).

**Comment by thijstriemstra** [comment]
Thanks for the response @alvestrand, I think I will file a bug because this is driving me nuts. MediaStream.stop() is deprecated in favor of MediaStreamTrack.stop() since Chrome M45 (https://developers.google.com/web/updates/2015/07/mediastream-deprecations), and this works, but unfortunately it doesn't in Firefox even though they plan to deprecate it as well (https://www.fxsitecompat.com/en-US/docs/2015/mediastream-stop-has-been-deprecated/).
