### ISSUE TITLE
Troubleshooting Page

### ISSUE THREAD

**Issue by bennycode** [webrtcHacks/adapter#724]
Hi, is there an online test page (like [WebRTC Troubleshooter](https://test.webrtc.org)) which includes the `webrtc-adapter` and can be used to test it's compatibility in real browsers?

**Comment by KaptenJansson** [comment]
WebRTC troubleshooter does use webrtc-adapter but not with the purpose of testing compatability per see.

Also all the tests run automatically in Chrome and Firefox since they are easy to test on Travis. Edge and Safari (they are a bit trickier since they require specific OS's) could be tested using Travis and Browserstack together but we do not have the resources to maintain that kind of infra right now.

There is also https://github.com/webrtc/KITE but be warned it's a huge E2E test framework, it does use AppRTC which also uses webrtc-adapter.
