### ISSUE TITLE
Should adapter detect this as a constraints error?

### ISSUE THREAD

**Issue by getify** [webrtcHacks/adapter#828]
Referring to this issue: https://github.com/webrtc/samples/issues/955

I'm running into this same problem with my macbook air and chrome 67. On this webrtc-samples demo page: https://webrtc.github.io/samples/src/content/getusermedia/resolution/ If I select "Full HD", it comes back with a black 2x2 video.

I'm posting here because I was about to file this as a bug with Chrome (I dunno -- is it a bug with the browser or with my macbook itself?), but I realized that also it seems like this could/should be detected and "fixed" (ie, exception thrown) by the adapter?

My work-around is to try the video on a hidden `<video>` element, and wait for its dimensions meta data, and if it's not what I requested (1920x1080), like instead 2x2, assume it was a constraints error, and move on.

It would be helpful if maybe the adapter (call to `getUserMedia(..)`) could just do that, though, patching up what is either a Chrome or device bug in this respect. I suspect there are a lot of people with macbook airs and chrome, for whom this is happening.

**Comment by getify** [comment]
Filed this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=850658

**Comment by fippo** [comment]
paging @guidou but @jan-ivar might have an opinion too

**Comment by nils-ohlmeier** [comment]
According to this https://www.apple.com/macbook-air/specs/ your cam supports only 720p as the max resolution. I think that is in fact true for all build cams on Apple laptops. It's pretty sad compared to the cams they build into the phones.

**Comment by nils-ohlmeier** [comment]
For what it's worth I do get an OverConstrainedError on Firefox 62 on my MacBook Pro, which has the same 720p cam as the Air. So looks like a Chrome bug to me.

**Comment by fippo** [comment]
@getify can you check what the "video capture" tab on chrome://media-internals/ shows? (I think you need to call getUserMedia at least once)
This should return an OverConstrainedError and at least on my machine (dell xps 13) it does for a camera that only supports 720p

The sample currently shows exact constraints which is good for QA but probably not what a user is looking for.

**Comment by getify** [comment]
![media-internals](https://user-images.githubusercontent.com/150330/41178569-55c290c0-6b2d-11e8-852e-370a8c7b8cf6.png)

Perhaps the problem is that "WebPluginVirtualCamera"? I have no idea what that is or where that came from, other than perhaps from Google Hangouts (the only WebRTC'ish thing I do on this machine).

**Comment by getify** [comment]
Also, the point of *this* bug I've filed is only to track whether if, for whatever reason, a browser/OS/machine hands out an invalid video stream, adapter should "fix" that as it does other cross-browser inconsistencies?

As I said, I've filed bugs to track whether it's ultimately a Chrome (or OSX or Macbook Air) bug. But regardless of that, I'd still like it if adapter handled this "test the video stream to see if it's legit" thing. Perhaps there are other odd cases besides mine where invalid videos are returned, and such a feature would "fix" all of them.

**Comment by fippo** [comment]
that device *might* cause the bad behaviour but it seems a bit unlikely that @rantonysamy has the same device. Ravi: can you get a media-internals screenshot too?

Currently this looks like a nasty bug. While searching for the original issue with those not-actually-ready streams (maybe @aullman remembers?)
I found https://bugs.chromium.org/p/chromium/issues/detail?id=684288 so tagging @Orphis (and wondering why that bug is not marked as fixed)

also yay for qualified bugs that are fun to triage!

**Comment by nils-ohlmeier** [comment]
I just tested this on a 2013 MacBook Air. And it work like expected with OverConstrainedErrors, no black video.

Here is the screen shot from that device
![screen shot 2018-06-08 at 1 42 44 pm](https://user-images.githubusercontent.com/6109500/41180156-2991cd64-6b22-11e8-8c05-d1bb309076f0.jpeg)

**Comment by jan-ivar** [comment]
> I'd still like it if adapter handled this "test the video stream to see if it's legit" thing.

@getify If this affected all macbook airs maybe, but it sounds rare. Also note that `getUserMedia` in both Chrome and Firefox [succeed early](https://jsfiddle.net/jib1/uv35cwen/9/) (by about 1-2 seconds for me) before any data is received on the video track. So a verification step would alter the timing quite a bit compared to non-adapter use.

> WebPluginVirtualCamera

Have you tried  uninstalling Vidyo?

**Comment by getify** [comment]
> Have you tried uninstalling Vidyo?

I don't know what Vidyo is but I don't recall ever installing it, and it's not in my Applications.

Is there some other way to uninstall "WebPluginVirtualCamera"?

**Comment by getify** [comment]
> So a verification step would alter the timing quite a bit compared to non-adapter use.

I'm having to pay that time penalty in my code because this bug happens to be affecting my machine and so I have no other option. The downside is, I'll have to re-invent this checking code for every webrtc project I come across -- would be tough to abstract it into a reusable lib itself that wasn't already wrapping up `getUserMedia(..)` like adapter is. IOW, it just seems natural for such behavior to be co-located with something that's already "fixing" that same function.

I understand why others might not want to pay the time penalty by default. Any chance for this to be an option like some obscure config flag (setting a Symbol on `getUserMedia(..)` for example) so that those (like me) who need the extra testing can opt-in?

**Comment by jan-ivar** [comment]
Let's figure out where the bug is first, to understand its scope, and any possible workarounds. If this is a Chrome bug, they'll hopefully fix it asap.

Until then, you could do something like this:
```js
async function getUserMedia(constraints) {
  const stream = await navigator.mediaDevices.getUserMedia(constraints);
  const v = document.createElement("video");
  v.srcObject = stream;
  await new Promise(r => v.addEventListener("loadedmetadata", r, {once: true}));
  if (v.videoWidth < 10 || v.videoHeight < 10) {
    throw new DOMException("Constraints could be not satisfied.",
                           "OverconstrainedError");
  }
  v.srcObject = null;
  return stream;
}
```

This is really limited however. E.g. if someone did `getUserMedia({video: {width: 9999}})` they expect the highest *working* resolution, not an error. There's no feasible workaround for that that wouldn't incur double permission prompts in some browsers (like Firefox).

**Comment by jan-ivar** [comment]
And that workaround would throw *after* the Firefox permission prompt, not before, which is problematic.

**Comment by nils-ohlmeier** [comment]
I would say that expect adapter.js to unify the API between browsers. But it's not the place to protect against all kind of broken audio and video devices.
I also think that @jan-ivar is right that we need to find out if this "WebPluginVirtualCamera" is causing your problems. And where you got it from (I think @jan-ivar asked about Vidyo, because the first hits on a Google search are related to Vidyo).

**Comment by getify** [comment]
> If someone did getUserMedia({video: {width: 9999}}) they expect the highest working resolution

I wish. This is not how it actually works, at least not for my code in my Chrome. The `width: 9999` should in theory imply `width: { ideal: 9999 }`, and thus you should just get the highest that matches. But my experience (possibly tainted by this bug?) is that if the ideal is too far above the available, it fails with over-constrained.

For example, my system supports and gives me 1280x720 just fine, but if I ask for `{ width: 1280, height: 1280 }` -- IOW, I want either 1280x720 or 720x1280 -- it fails for me with over-constrained. That's true not only on my macbook air, but also on my android phone which also has a 720p front-facing camera. So `{ width: 1280, height: 720 }` works fine, as does `{ width: 720, height: 1280 }`, but `{ width: 1280, height: 1280 }` doesn't.

My take-away is that while I would *like* to just be able to ask for the "best" resolution supported, and I *wish* the API worked that way, in reality it doesn't. In my app, I've had to implement an algorithm that tries each specific known resolution (using `exact`) in descending order, until it finds one that works. Then I save that data in sessionStorage/localStorage so I don't keep re-testing the device unnecessarily.

The extra wrinkle of this bug is that even when I get a stream back, I have to also test to make sure it wasn't a false-positive where the video stream won't actually work.

**Comment by jan-ivar** [comment]
> My take-away is that while I would like to just be able to ask for the "best" resolution supported, and I wish the API worked that way, in reality it doesn't.

As defined, it does. See the [spec](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-fitness-distance) and [try it](https://jsfiddle.net/jib1/3hksbngx/) in Firefox. Please [file a bug](https://bugs.chromium.org/p/chromium/issues/list?q=constraints+component%3ABlink%3EGetUserMedia+) on Chrome.

The role of adapter is to polyfill the spec where possible. You're welcome to try to improve [my crude ideal polyfill for Chrome from 3 years ago](https://github.com/webrtc/adapter/pull/31) on this—it only works for direct-match values—but TBH I didn't expect it to still be around.

**Comment by jan-ivar** [comment]
Back to the issue at hand, we need to A) know which browsers are affected (please try other browsers), and B) repro this on more than one system. This is to know the scope and course of mitigation to pursue.

If this turns out to be a Chrome bug, that'd be good news as `OverconstrainedError` can really only be polyfilled on Chrome (because Chrome persists permissions implicitly). I'd actually *prefer* we fix it in adapter then because it'd contain this hack to Chrome and potentially avoid breaking Firefox users.

But I'm getting ahead of myself.

**Comment by getify** [comment]
In Firefox 62, if I try "Full HD", it opens a permissions prompt and only lists that "WebPluginVirtualCamera". If I try that feed, I get a blank video (not the black 2x2, but just totally blank).

If I instead try "HD", Firefox asks me to pick either my webcam or this plugin. So, it appears that Firefox filters that list of devices based on the constraints provided?

It seems like maybe the presence of this plugin is the culprit, in that it's advertising itself as supporting 1920x1080, but not actually able to feed any video to that resolution. So both Chrome and Firefox are taking it at its word and being fooled. It's slightly strange to me that they have different failures (one 2x2 black, the other just nothing), but it seems like both are choking on trying to use this plugin and being unable to.

As I said earlier, I also can't figure out how to uninstall this plugin.

**Comment by jan-ivar** [comment]
> So, it appears that Firefox filters that list of devices based on the constraints provided?

Yes, to spec, as does Chrome—without showing the list to user—so that explains it. Bad device.

**Comment by guidou** [comment]
The 2x2 black frame appears because Chrome's video element implementation always plays a 2x2 frame after the track is closed in order to clear the last frame from the closed track. 
When it's a functional device that has produced frames with the requested resolution, the black frame in the video element will appear with the same dimensions as the previous frames.
In this case we just have a faulty device that never produced a single frame, the track was closed and the 2x2 frame was the only frame played by the element, hence the 2x2 dimension of the element.
This is working as intended in Chrome and I think it's not against the spec since the 2x2 frame is played by the element after the track is closed.
Firefox uses a different mechanism, but to me, both implementations seem to be working as per the spec.

**Comment by fippo** [comment]
Nothing adapter can do here really :-|

**Comment by getify** [comment]
> I also can't figure out how to uninstall this plugin.

Does anyone happen to have any suggestions on how I can forcibly uninstall this plugin?

I don't have the original software that it supposedly came from, and following the instructions they have on their website also doesn't work.
