### ISSUE TITLE
Error in browser with adblock extension + webrtc-adapter

### ISSUE THREAD

**Issue by 1tu** [webrtcHacks/adapter#831]
- [ ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected
**Browser - Chrome 67.0.3396.87**
**adapter.js - v6.1.5**
**adblock extension - now..**

## Description
it appears only if the adblock extension is installed.
attached the screenshots with the exact places where there is a bug
----
![2018-06-14_17-18-05](https://user-images.githubusercontent.com/11233069/41418375-3b6302bc-6ff8-11e8-93f8-6190c239d035.png)
---
![2018-06-14_17-18-45](https://user-images.githubusercontent.com/11233069/41418376-3b895d90-6ff8-11e8-905d-19d874e77d93.png)
---
![2018-06-14_17-20-11](https://user-images.githubusercontent.com/11233069/41418377-3bb1f016-6ff8-11e8-8d72-5254581ba1ef.png)

## Steps to reproduce
1) Install adblock extension
2) Use application with `webrtc-adapter`
3) Try to connect to other user (must execute `new RTCPeerConnection(...)`)

## Expected results
works fine, no error

## Actual results
```
Uncaught (in promise) TypeError: Cannot assign to read only property 'iceServers' of object '#<Object>'
window.RTCPeerConnection | @ | chrome_shim.js?fa98:597
WrappedRTCPeerConnection | @ | blob:http://localhos…6d-31ed32b197c2:300
...
```

**Comment by fippo** [comment]
IIRC adblock has the nasty property of removing window.RTCPeerConnection.
I don't understand why this would throw at the line you indicate though and not the next one.

You should always check support by checking whether `window.RTCPeerConnection` and `navigator.mediaDevices.getUserMedia` exist before calling them.

**Comment by danbriggs5** [comment]
I was getting a the same error awhile back using [Adblock Plus](https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb) and filed [a bug report](https://adblockplus.org/forum/viewtopic.php?f=10&t=55483) on their forum. I also defined some quick steps in there for reproducing this issue using the webrtc trickle example.

It looks like this is now happening with the regular [Adblock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom) extension as well.

@fippo I'm not sure this is just a case of checking for the existence of webrtc methods on the window object. At least in my case, the window methods are defined.

I believe the issue is caused by adblock wrapping the pc methods and using `Object.defineProperty` to add properties to the `pcConfig` object. That would make the `iceServers` key immutable and cause the error above. AddBlock Plus has their code on github so you can see their implementation [here.](https://github.com/adblockplus/adblockpluschrome/blob/master/inject.preload.js)

This could be solved by creating a copy of the pcConfig object that replaces the immutable properties with mutable properties. Here is an example using the snippet that is throwing the error:
```javascript
// migrate from non-spec RTCIceServer.url to RTCIceServer.urls
var OrigPeerConnection = window.RTCPeerConnection;
window.RTCPeerConnection = function(pcConfig, pcConstraints) {
  const configCopy = {};
  Object.getOwnPropertyNames(pcConfig).forEach(function(name) {
    configCopy[name] = pcConfig[name];
  });
  if (configCopy && configCopy.iceServers) {
    var newIceServers = [];
    for (var i = 0; i < configCopy.iceServers.length; i++) {
      var server = configCopy.iceServers[i];
      if (!server.hasOwnProperty('urls') &&
          server.hasOwnProperty('url')) {
        utils.deprecated('RTCIceServer.url', 'RTCIceServer.urls');
        server = JSON.parse(JSON.stringify(server));
        server.urls = server.url;
        newIceServers.push(server);
      } else {
        newIceServers.push(configCopy.iceServers[i]);
      }
    }
    configCopy.iceServers = newIceServers;
  }
  return new OrigPeerConnection(configCopy, pcConstraints);
```

Not sure if this is something you would want to add or not :)

**Comment by lgrahl** [comment]
All this monkey patching is causing me headaches.

**Comment by danbriggs5** [comment]
I don't seem to be getting this error anymore. Still using the same adapter version so it's possible something changed with Adblock. Could also be some other factor I'm forgetting about. @1tu are you still getting this?
