### ISSUE TITLE
Supported browsers

### ISSUE THREAD

**Issue by arusak** [webrtcHacks/adapter#894]
Thank you for you effort to make cross-browser WebRTC development easier. I have a few questions about compatibility.

- What browsers does this library support? 
- Does it target all versions of Chrome, Edge, FF and Safari, or older releases are not supported? 
- What about mobile versions? 

Couldn't find any information on this topic.

**Comment by fippo** [comment]
Chrome, Firefox, Safari and Edge are supported. There are tests for Electron as well, mostly because that was cheap to add.
Reasonably old releases (less than a year) should still work without problems. For Firefox the tests cover the ESR version.

**Comment by arusak** [comment]
What about mobile Chrome and iOS Safari? Do you expect the adapter to work in those browsers?

**Comment by fippo** [comment]
Yes. @dagingaa uses them happily

**Comment by dagingaa** [comment]
Yeah, we've been using WebRTC on iOS in production with adapter for almost a year now (ever since the initial public release of WebRTC in Safari). Adapter has done a good job so far :)

Shameless plug: You can test it out in Safari here https://confrere.com/test/, sadly we haven't had the time to port the network tester yet, which tests connectivity as well, this is only available inside our actual application.

**Comment by dagingaa** [comment]
Note: iOS has a LOT of ifs and buts. https://webrtchacks.com/guide-to-safari-webrtc/ is a good article to get you started.

**Comment by arusak** [comment]
Thank you gentlemen.
